#!/usr/bin/env python3
"""
Cyber Security News Application
A daily cybersecurity news aggregator and reader

Author: Generated by AI Assistant
License: MIT
"""

import argparse
import asyncio
import sys
from datetime import datetime
from typing import List, Dict

from src.news_aggregator import NewsAggregator
from src.config import Config
from src.cli_interface import CLIInterface


def main():
    """Main application entry point"""
    parser = argparse.ArgumentParser(
        description="Cybersecurity News Application - Get daily cybersecurity news from multiple sources"
    )
    
    parser.add_argument(
        "--update", 
        action="store_true", 
        help="Fetch latest news from all sources"
    )
    
    parser.add_argument(
        "--show", 
        action="store_true", 
        help="Display latest cybersecurity news"
    )
    
    parser.add_argument(
        "--categories", 
        nargs="+", 
        help="Filter news by categories (vulnerabilities, breaches, malware, etc.)"
    )
    
    parser.add_argument(
        "--sources", 
        nargs="+", 
        help="Specify news sources to fetch from"
    )
    
    parser.add_argument(
        "--days", 
        type=int, 
        default=1, 
        help="Number of days of news to retrieve (default: 1)"
    )
    
    parser.add_argument(
        "--web", 
        action="store_true", 
        help="Start web interface"
    )
    
    parser.add_argument(
        "--daemon", 
        action="store_true", 
        help="Run as daemon with scheduled updates"
    )
    
    parser.add_argument(
        "--schedule-status", 
        action="store_true", 
        help="Show scheduler status"
    )
    
    parser.add_argument(
        "--sources-list", 
        action="store_true", 
        help="List configured news sources"
    )
    
    parser.add_argument(
        "--stats", 
        action="store_true", 
        help="Show news statistics"
    )
    
    parser.add_argument(
        "--export", 
        choices=["json", "csv"], 
        help="Export articles to file (json or csv)"
    )
    
    args = parser.parse_args()
    
    # Initialize components
    config = Config()
    aggregator = NewsAggregator(config)
    cli = CLIInterface(config)
    
    try:
        if args.web:
            # Start web interface
            from src.web_interface import start_web_server
            start_web_server()
        elif args.daemon:
            # Start scheduler daemon
            from src.scheduler import run_daemon
            run_daemon()
        elif args.schedule_status:
            # Show scheduler status
            from src.scheduler import NewsScheduler
            scheduler = NewsScheduler(config)
            status = scheduler.get_status()
            cli._print_message(f"Scheduler Status: {'Running' if status['is_running'] else 'Stopped'}", "info")
            cli._print_message(f"Scheduled Jobs: {status['scheduled_jobs']}", "info")
            cli._print_message(f"Last Update: {status['last_update']}", "info")
        elif args.sources_list:
            # List sources
            cli.show_sources()
        elif args.stats:
            # Show statistics
            cli.show_statistics()
        elif args.export:
            # Export articles
            cli.export_articles(format_type=args.export, days=args.days)
        elif args.update:
            # Fetch latest news
            print("🔄 Fetching latest cybersecurity news...")
            asyncio.run(aggregator.update_news())
            print("✅ News update completed!")
        elif args.show:
            # Display news
            cli.display_news(
                categories=args.categories,
                sources=args.sources,
                days=args.days
            )
        else:
            # Default: show today's news
            print("📰 Today's Cybersecurity News")
            print("=" * 50)
            cli.display_news(days=1)
            
    except KeyboardInterrupt:
        print("\n👋 Goodbye!")
        sys.exit(0)
    except Exception as e:
        print(f"❌ Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()